/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cursoemvideo;

/**
 *
 * @author LuisDaviVieiraSilva
 */
public class OperadoresRelacionaisJava extends javax.swing.JFrame {

    /**
     * Creates new form OperadoresRelacionaisJava
     */
    public OperadoresRelacionaisJava() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPrimeiroValor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSegundoValor = new javax.swing.JTextField();
        btnMaiorQue = new javax.swing.JButton();
        btnMenorQue = new javax.swing.JButton();
        btnMaiorIgual = new javax.swing.JButton();
        btnMenorIgual = new javax.swing.JButton();
        btnIgualIgual = new javax.swing.JButton();
        btnDiferenteIgual = new javax.swing.JButton();
        lblFT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("OPERADORES RELACIONADOS");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Digite o primeiro valor:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Digite o segundo valor:");

        btnMaiorQue.setText(">");
        btnMaiorQue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaiorQueActionPerformed(evt);
            }
        });

        btnMenorQue.setText("<");
        btnMenorQue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenorQueActionPerformed(evt);
            }
        });

        btnMaiorIgual.setText(">=");
        btnMaiorIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaiorIgualActionPerformed(evt);
            }
        });

        btnMenorIgual.setText("<=");
        btnMenorIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenorIgualActionPerformed(evt);
            }
        });

        btnIgualIgual.setText("==");
        btnIgualIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualIgualActionPerformed(evt);
            }
        });

        btnDiferenteIgual.setText("!=");
        btnDiferenteIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiferenteIgualActionPerformed(evt);
            }
        });

        lblFT.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblFT.setForeground(new java.awt.Color(255, 0, 0));
        lblFT.setText("FALSE OU TRUE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrimeiroValor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSegundoValor))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnMaiorQue, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMenorQue, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMaiorIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMenorIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIgualIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDiferenteIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(lblFT)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrimeiroValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSegundoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDiferenteIgual, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnIgualIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMaiorQue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenorQue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMaiorIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenorIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(lblFT)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaiorQueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaiorQueActionPerformed
        // TODO add your handling code here:
        int pv = Integer.parseInt(txtPrimeiroValor.getText());
        int sv = Integer.parseInt(txtSegundoValor.getText());
        String resultado = (pv > sv)?"Verdadeiro":"Falso";
        lblFT.setText(resultado);
    }//GEN-LAST:event_btnMaiorQueActionPerformed

    private void btnMenorQueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenorQueActionPerformed
        // TODO add your handling code here:
        int pv = Integer.parseInt(txtPrimeiroValor.getText());
        int sv = Integer.parseInt(txtSegundoValor.getText());
        String resultado = (pv < sv)?"Verdadeiro":"Falso";
        lblFT.setText(resultado);
    }//GEN-LAST:event_btnMenorQueActionPerformed

    private void btnMaiorIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaiorIgualActionPerformed
        // TODO add your handling code here:
        int pv = Integer.parseInt(txtPrimeiroValor.getText());
        int sv = Integer.parseInt(txtSegundoValor.getText());
        String resultado = (pv >= sv)?"Verdadeiro":"Falso";
        lblFT.setText(resultado);
    }//GEN-LAST:event_btnMaiorIgualActionPerformed

    private void btnMenorIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenorIgualActionPerformed
        // TODO add your handling code here:
        int pv = Integer.parseInt(txtPrimeiroValor.getText());
        int sv = Integer.parseInt(txtSegundoValor.getText());
        String resultado = (pv <= sv)?"Verdadeiro":"Falso";
        lblFT.setText(resultado);
    }//GEN-LAST:event_btnMenorIgualActionPerformed

    private void btnIgualIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualIgualActionPerformed
        // TODO add your handling code here:
        int pv = Integer.parseInt(txtPrimeiroValor.getText());
        int sv = Integer.parseInt(txtSegundoValor.getText());
        String resultado = (pv == sv)?"Verdadeiro":"Falso";
        lblFT.setText(resultado);
    }//GEN-LAST:event_btnIgualIgualActionPerformed

    private void btnDiferenteIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiferenteIgualActionPerformed
        // TODO add your handling code here:
        int pv = Integer.parseInt(txtPrimeiroValor.getText());
        int sv = Integer.parseInt(txtSegundoValor.getText());
        String resultado = (pv != sv)?"Verdadeiro":"Falso";
        lblFT.setText(resultado);
    }//GEN-LAST:event_btnDiferenteIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperadoresRelacionaisJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperadoresRelacionaisJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperadoresRelacionaisJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperadoresRelacionaisJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperadoresRelacionaisJava().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiferenteIgual;
    private javax.swing.JButton btnIgualIgual;
    private javax.swing.JButton btnMaiorIgual;
    private javax.swing.JButton btnMaiorQue;
    private javax.swing.JButton btnMenorIgual;
    private javax.swing.JButton btnMenorQue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblFT;
    private javax.swing.JTextField txtPrimeiroValor;
    private javax.swing.JTextField txtSegundoValor;
    // End of variables declaration//GEN-END:variables
}
